# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kcoreaddons': '@stable'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
